# Generated by Django 6.0.1 on 2026-05-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_participant_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('instant', 'Instant'), ('scheduled', 'Scheduled')], default='instant', max_length=20),
        ),
    ]
