# Generated by Django 6.0.5 on 2026-05-22 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_meeting_participants_participant_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['host', 'created_at'], name='meetings_me_host_id_50a902_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['meeting', 'is_active'], name='meetings_pa_meeting_524b03_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['meeting', 'joined_at'], name='meetings_pa_meeting_539ead_idx'),
        ),
    ]
