# Generated by Django 6.0.5 on 2026-05-22 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_participant_is_host_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('chat', 'Chat Message'), ('system', 'System Notification'), ('control', 'Control Command')], default='chat', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='reconnect_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('meeting', 'user'), name='unique_meeting_user'),
        ),
    ]
