# Generated by Django 6.0.5 on 2026-05-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_chatmessage_message_type_participant_reconnect_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
